// ───────────────────────────── @elio/studio — Static preview generator ─────────────────────────────
// Produces packages/studio/preview/dashboard-preview.html: the EXACT same dashboard CSS/markup/JS as the
// served page (imported from the built dist so it can never drift from the real dashboard), but driven by
// the inlined sample data (window.ELIO_SAMPLE) instead of the live API — so the design can be reviewed
// WITHOUT running the server. Self-contained: no external requests, no <script> that needs the API.
//
// Run: pnpm --filter @elio/studio build && node packages/studio/preview/build-preview.mjs
// The committed dashboard-preview.html is the output of this script.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { DASHBOARD_CSS, DASHBOARD_BODY, DASHBOARD_JS, DASHBOARD_MARKER } from "../dist/dashboard.js";
import { sample } from "./sample-data.mjs";

const here = dirname(fileURLToPath(import.meta.url));

// Inline the sample as a JSON literal (no executable injection): the dashboard JS reads the global
// ELIO_SAMPLE and renders from it in STATIC mode (no fetch, no SSE, resume disabled).
const sampleJson = JSON.stringify(sample, null, 2);

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>ELIO Studio — preview</title>
<!--
  STATIC PREVIEW SNAPSHOT — generated by preview/build-preview.mjs.
  Same dashboard as GET / (CSS/markup/JS imported from dist), driven by inlined sample data.
  Self-contained: open this file directly in a browser, no server needed.
-->
<style>
${DASHBOARD_CSS}
</style>
</head>
<body data-app="${DASHBOARD_MARKER}">
${DASHBOARD_BODY}
<script>
var ELIO_SAMPLE = ${sampleJson};
</script>
<script>
${DASHBOARD_JS}
</script>
</body>
</html>`;

const out = join(here, "dashboard-preview.html");
writeFileSync(out, html, "utf8");
console.log(`dashboard-preview: wrote ${out} (${html.length} bytes)`);
